version: 'latest'

# 1. Definir las redes personalizadas
networks:
  inventario-network:
    driver: bridge

services:
# Definición del servicio postgres
  postgres:
    image: postgres:latest
    restart: always
    container_name: db_inventario
    environment:
      POSTGRES_DB: inventario
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin    
    ports:
      - 5434:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
     - inventario-network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5052:80
    networks:
      -  inventario-network # Red personalizada para conectar con el contenedor de postgres